name: GitHub Actions 

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate-m3u:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Create output directory
        run: mkdir -p ./output

      - name: Generate m3u list
        run: python main.py > ./output/rakuten.m3u
        # 移除了所有 env 代理配置，直接使用官方网络

      - name: Add updated list to repository
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Update Rakuten UK list without proxy"
          add: '*.m3u --force'
          cwd: './output/'
