name: GitHub Actions 

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate-m3u:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Create output directory
        run: mkdir -p ./output

      - name: Generate m3u list
        run: python main.py > ./output/rakuten.m3u
        env:
          # 使用这种方式可以避免拼接时出现多余的冒号或空格
          HTTP_PROXY: "http://${{ secrets.PROXY_USERNAME }}:${{ secrets.PROXY_PASSWORD }}@${{ secrets.PROXY_IP }}:5009"
          HTTPS_PROXY: "http://${{ secrets.PROXY_USERNAME }}:${{ secrets.PROXY_PASSWORD }}@${{ secrets.PROXY_IP }}:5009"

      - name: Add updated list to repository
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Update Rakuten UK list"
          add: '*.m3u --force'
          cwd: './output/'
